# Generated by Django 3.2.3 on 2021-05-18 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_wallet', to='wallet.wallet')),
                ('to_wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_wallet', to='wallet.wallet')),
            ],
        ),
    ]
